# Generated by Django 4.2.2 on 2023-07-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='link',
            new_name='video_link',
        ),
    ]
